# Generated by Django 4.2.4 on 2023-08-18 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventModel",
            fields=[
                ("eid", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=50)),
                (
                    "attendees",
                    models.ManyToManyField(default=None, related_name="attendees", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="owner", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
