# Generated by Django 4.2.4 on 2023-08-20 13:48


from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirlineModel",
            fields=[
                ("oid", models.AutoField(primary_key=True, serialize=False)),
                ("destination", models.CharField(max_length=30)),
                ("destination_IATA", models.CharField(max_length=15)),
                ("origin", models.CharField(max_length=30)),
                ("origin_IATA", models.CharField(max_length=15)),
                (
                    "ticket",
                    models.CharField(
                        choices=[("ONEWAY", "One-way"), ("RETURN", "Return")], default="ONEWAY", max_length=10
                    ),
                ),
                ("departure", models.DateField()),
                ("arrival", models.DateField(blank=True, null=True)),

            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE AirlineModel ADD COLUMN created_at TIMESTAMP DEFAULT (NOW() - INTERVAL '2 days');",
            "ALTER TABLE AirlineModel DROP COLUMN created_at;",
        ),
    ]
